name: firmware

# For now, this workflow is used for checks, not for releases.
# So all release stuff is commented out.

on:
  push:
    branches:
      - main
    # tags:
    #   - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request: {}

permissions:
  contents: write

jobs:
  keira:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
            ./firmware/keira/.pio
          key: ${{ runner.os }}-keira
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        working-directory: ./firmware/keira
        run: pio run -e v2

      - name: Copy firmware
        working-directory: ./firmware/keira
        run: |
          cp .pio/build/v2/firmware.bin keira.bin

      # - name: Upload firmware artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: keira-firmware
      #     path: ./firmware/keira/keira.bin

  doom:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
            ./firmware/doom/.pio
          key: ${{ runner.os }}-doom
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        working-directory: ./firmware/doom
        run: pio run -e v2

      - name: Copy firmware
        working-directory: ./firmware/doom
        run: |
          cp .pio/build/v2/firmware.bin doom.bin

      # - name: Upload firmware artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: doom-firmware
      #     path: ./firmware/doom/doom.bin

  # release:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - keira
  #     - doom
  #
  #   steps:
  #     - name: Download keira artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: keira-firmware
  #         path: .
  #     - name: Download doom artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: doom-firmware
  #         path: .
  #     - name: Release
  #       uses: softprops/action-gh-release@v2
  #       with:
  #         files: |
  #           keira.bin
  #           doom.bin
